/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xaccp.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2007
 * 
 * XDoclet definition:
 * @struts.form name="enterpriseForm"
 */
public class EnterpriseForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** enterpriseAddress property */
	private String enterpriseAddress;

	/** enterprisePass2 property */
	private String enterprisePass2;

	/** enterId property */
	private int enterId;

	/** enterpriseCompanyName property */
	private String enterpriseCompanyName;

	/** enterpriseEmail property */
	private String enterpriseEmail;

	/** enterpriseTel property */
	private String enterpriseTel;

	/** enterpriseName property */
	private String enterpriseName;

	/** enterpriseLinkMan property */
	private String enterpriseLinkMan;

	/** enterprisePass property */
	private String enterprisePass;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the enterpriseAddress.
	 * @return String
	 */
	public String getEnterpriseAddress() {
		return enterpriseAddress;
	}

	/** 
	 * Set the enterpriseAddress.
	 * @param enterpriseAddress The enterpriseAddress to set
	 */
	public void setEnterpriseAddress(String enterpriseAddress) {
		this.enterpriseAddress = enterpriseAddress;
	}

	/** 
	 * Returns the enterprisePass2.
	 * @return String
	 */
	public String getEnterprisePass2() {
		return enterprisePass2;
	}

	/** 
	 * Set the enterprisePass2.
	 * @param enterprisePass2 The enterprisePass2 to set
	 */
	public void setEnterprisePass2(String enterprisePass2) {
		this.enterprisePass2 = enterprisePass2;
	}

	/** 
	 * Returns the enterId.
	 * @return int
	 */
	public int getEnterId() {
		return enterId;
	}

	/** 
	 * Set the enterId.
	 * @param enterId The enterId to set
	 */
	public void setEnterId(int enterId) {
		this.enterId = enterId;
	}

	/** 
	 * Returns the enterpriseCompanyName.
	 * @return String
	 */
	public String getEnterpriseCompanyName() {
		return enterpriseCompanyName;
	}

	/** 
	 * Set the enterpriseCompanyName.
	 * @param enterpriseCompanyName The enterpriseCompanyName to set
	 */
	public void setEnterpriseCompanyName(String enterpriseCompanyName) {
		this.enterpriseCompanyName = enterpriseCompanyName;
	}

	/** 
	 * Returns the enterpriseEmail.
	 * @return String
	 */
	public String getEnterpriseEmail() {
		return enterpriseEmail;
	}

	/** 
	 * Set the enterpriseEmail.
	 * @param enterpriseEmail The enterpriseEmail to set
	 */
	public void setEnterpriseEmail(String enterpriseEmail) {
		this.enterpriseEmail = enterpriseEmail;
	}

	/** 
	 * Returns the enterpriseTel.
	 * @return String
	 */
	public String getEnterpriseTel() {
		return enterpriseTel;
	}

	/** 
	 * Set the enterpriseTel.
	 * @param enterpriseTel The enterpriseTel to set
	 */
	public void setEnterpriseTel(String enterpriseTel) {
		this.enterpriseTel = enterpriseTel;
	}

	/** 
	 * Returns the enterpriseName.
	 * @return String
	 */
	public String getEnterpriseName() {
		return enterpriseName;
	}

	/** 
	 * Set the enterpriseName.
	 * @param enterpriseName The enterpriseName to set
	 */
	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	/** 
	 * Returns the enterpriseLinkMan.
	 * @return String
	 */
	public String getEnterpriseLinkMan() {
		return enterpriseLinkMan;
	}

	/** 
	 * Set the enterpriseLinkMan.
	 * @param enterpriseLinkMan The enterpriseLinkMan to set
	 */
	public void setEnterpriseLinkMan(String enterpriseLinkMan) {
		this.enterpriseLinkMan = enterpriseLinkMan;
	}

	/** 
	 * Returns the enterprisePass.
	 * @return String
	 */
	public String getEnterprisePass() {
		return enterprisePass;
	}

	/** 
	 * Set the enterprisePass.
	 * @param enterprisePass The enterprisePass to set
	 */
	public void setEnterprisePass(String enterprisePass) {
		this.enterprisePass = enterprisePass;
	}
}