/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xaccp.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2007
 * 
 * XDoclet definition:
 * @struts.form name="userInfoForm"
 */
public class UserInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** paperCode property */
	private String paperCode;

	/** realName property */
	private String realName;

	/** userPass1 property */
	private String userPass1;

	/** userName property */
	private String userName;

	/** uemail property */
	private String uemail;

	/** userId property */
	private int userId;

	/** userSex property */
	private int userSex;

	/** userPass2 property */
	private String userPass2;

	/** userTel property */
	private String userTel;

	/** uaddress property */
	private String uaddress;

	/** userAge property */
	private int userAge;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the paperCode.
	 * @return String
	 */
	public String getPaperCode() {
		return paperCode;
	}

	/** 
	 * Set the paperCode.
	 * @param paperCode The paperCode to set
	 */
	public void setPaperCode(String paperCode) {
		this.paperCode = paperCode;
	}

	/** 
	 * Returns the realName.
	 * @return String
	 */
	public String getRealName() {
		return realName;
	}

	/** 
	 * Set the realName.
	 * @param realName The realName to set
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/** 
	 * Returns the userPass1.
	 * @return String
	 */
	public String getUserPass1() {
		return userPass1;
	}

	/** 
	 * Set the userPass1.
	 * @param userPass1 The userPass1 to set
	 */
	public void setUserPass1(String userPass1) {
		this.userPass1 = userPass1;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the uemail.
	 * @return String
	 */
	public String getUemail() {
		return uemail;
	}

	/** 
	 * Set the uemail.
	 * @param uemail The uemail to set
	 */
	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the userSex.
	 * @return int
	 */
	public int getUserSex() {
		return userSex;
	}

	/** 
	 * Set the userSex.
	 * @param userSex The userSex to set
	 */
	public void setUserSex(int userSex) {
		this.userSex = userSex;
	}

	/** 
	 * Returns the userPass2.
	 * @return String
	 */
	public String getUserPass2() {
		return userPass2;
	}

	/** 
	 * Set the userPass2.
	 * @param userPass2 The userPass2 to set
	 */
	public void setUserPass2(String userPass2) {
		this.userPass2 = userPass2;
	}

	/** 
	 * Returns the userTel.
	 * @return String
	 */
	public String getUserTel() {
		return userTel;
	}

	/** 
	 * Set the userTel.
	 * @param userTel The userTel to set
	 */
	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	/** 
	 * Returns the uaddress.
	 * @return String
	 */
	public String getUaddress() {
		return uaddress;
	}

	/** 
	 * Set the uaddress.
	 * @param uaddress The uaddress to set
	 */
	public void setUaddress(String uaddress) {
		this.uaddress = uaddress;
	}

	/** 
	 * Returns the userAge.
	 * @return int
	 */
	public int getUserAge() {
		return userAge;
	}

	/** 
	 * Set the userAge.
	 * @param userAge The userAge to set
	 */
	public void setUserAge(int userAge) {
		this.userAge = userAge;
	}
}