package com.xaccp.po;



/**
 * Credit generated by MyEclipse - Hibernate Tools
 */

public class Credit  implements java.io.Serializable {


    // Fields    

     private Integer CId;
     private UserInfo userInfo;
     private Integer UCount;


    // Constructors

    /** default constructor */
    public Credit() {
    }

	/** minimal constructor */
    public Credit(Integer CId) {
        this.CId = CId;
    }
    
    /** full constructor */
    public Credit(Integer CId, UserInfo userInfo, Integer UCount) {
        this.CId = CId;
        this.userInfo = userInfo;
        this.UCount = UCount;
    }

   
    // Property accessors

    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }

    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    public Integer getUCount() {
        return this.UCount;
    }
    
    public void setUCount(Integer UCount) {
        this.UCount = UCount;
    }
   








}