package com.xaccp.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * FoodInfo generated by MyEclipse - Hibernate Tools
 */

public class FoodInfo  implements java.io.Serializable {


    // Fields    

	 private Integer FId;
     private EnterpriseInfo enterpriseInfo;
     private FoodSmallType foodSmallType;
     private String FName;
     private Double FPrice;
     private String FFrom;
     private String FImage;
     private Integer FState;
     private Date FDate;
     private Set orderInfos = new HashSet(0);


    // Constructors

	/** default constructor */
    public FoodInfo() {
    }

	/** minimal constructor */
    public FoodInfo(Integer FId, String FName, Double FPrice) {
        this.FId = FId;
        this.FName = FName;
        this.FPrice = FPrice;
    }
    
    /** full constructor */
    public FoodInfo(Integer id, EnterpriseInfo enterpriseInfo, FoodSmallType foodSmallType, String name, Double price, String from, String image, Integer state, Date date, Set orderInfos) {
		super();
		FId = id;
		this.enterpriseInfo = enterpriseInfo;
		this.foodSmallType = foodSmallType;
		FName = name;
		FPrice = price;
		FFrom = from;
		FImage = image;
		FState = state;
		FDate = date;
		this.orderInfos = orderInfos;
	}

   
    // Property accessors

    public Integer getFId() {
        return this.FId;
    }
    
    public void setFId(Integer FId) {
        this.FId = FId;
    }

    public EnterpriseInfo getEnterpriseInfo() {
        return this.enterpriseInfo;
    }
    
    public void setEnterpriseInfo(EnterpriseInfo enterpriseInfo) {
        this.enterpriseInfo = enterpriseInfo;
    }

    public FoodSmallType getFoodSmallType() {
        return this.foodSmallType;
    }
    
    public void setFoodSmallType(FoodSmallType foodSmallType) {
        this.foodSmallType = foodSmallType;
    }

    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }

    public Double getFPrice() {
        return this.FPrice;
    }
    
    public void setFPrice(Double FPrice) {
        this.FPrice = FPrice;
    }

    public String getFFrom() {
        return this.FFrom;
    }
    
    public void setFFrom(String FFrom) {
        this.FFrom = FFrom;
    }

    public String getFImage() {
        return this.FImage;
    }
    
    public void setFImage(String FImage) {
        this.FImage = FImage;
    }

    public Set getOrderInfos() {
        return this.orderInfos;
    }
    
    public void setOrderInfos(Set orderInfos) {
        this.orderInfos = orderInfos;
    }

	public Date getFDate() {
		return FDate;
	}

	public void setFDate(Date date) {
		FDate = date;
	}

	public Integer getFState() {
		return FState;
	}

	public void setFState(Integer state) {
		FState = state;
	}
}