package com.xaccp.po;

import java.util.HashSet;
import java.util.Set;


/**
 * FoodBigType generated by MyEclipse - Hibernate Tools
 */

public class FoodBigType  implements java.io.Serializable {


    // Fields    

     private Integer fbtId;
     private String fbtName;
     private Set foodSmallTypes = new HashSet(0);


    // Constructors

    /** default constructor */
    public FoodBigType() {
    }

	/** minimal constructor */
    public FoodBigType(Integer fbtId, String fbtName) {
        this.fbtId = fbtId;
        this.fbtName = fbtName;
    }
    
    /** full constructor */
    public FoodBigType(Integer fbtId, String fbtName, Set foodSmallTypes) {
        this.fbtId = fbtId;
        this.fbtName = fbtName;
        this.foodSmallTypes = foodSmallTypes;
    }

   
    // Property accessors

    public Integer getFbtId() {
        return this.fbtId;
    }
    
    public void setFbtId(Integer fbtId) {
        this.fbtId = fbtId;
    }

    public String getFbtName() {
        return this.fbtName;
    }
    
    public void setFbtName(String fbtName) {
        this.fbtName = fbtName;
    }

    public Set getFoodSmallTypes() {
        return this.foodSmallTypes;
    }
    
    public void setFoodSmallTypes(Set foodSmallTypes) {
        this.foodSmallTypes = foodSmallTypes;
    }
   








}