package com.xaccp.po;

import java.util.HashSet;
import java.util.Set;


/**
 * FoodSmallType generated by MyEclipse - Hibernate Tools
 */

public class FoodSmallType  implements java.io.Serializable {


    // Fields    

     private Integer fstId;
     private FoodBigType foodBigType;
     private String fstName;
     private Set foodInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public FoodSmallType() {
    }

	/** minimal constructor */
    public FoodSmallType(Integer fstId, String fstName) {
        this.fstId = fstId;
        this.fstName = fstName;
    }
    
    /** full constructor */
    public FoodSmallType(Integer fstId, FoodBigType foodBigType, String fstName, Set foodInfos) {
        this.fstId = fstId;
        this.foodBigType = foodBigType;
        this.fstName = fstName;
        this.foodInfos = foodInfos;
    }

   
    // Property accessors

    public Integer getFstId() {
        return this.fstId;
    }
    
    public void setFstId(Integer fstId) {
        this.fstId = fstId;
    }

    public FoodBigType getFoodBigType() {
        return this.foodBigType;
    }
    
    public void setFoodBigType(FoodBigType foodBigType) {
        this.foodBigType = foodBigType;
    }

    public String getFstName() {
        return this.fstName;
    }
    
    public void setFstName(String fstName) {
        this.fstName = fstName;
    }

    public Set getFoodInfos() {
        return this.foodInfos;
    }
    
    public void setFoodInfos(Set foodInfos) {
        this.foodInfos = foodInfos;
    }
   








}