package com.xaccp.po;



/**
 * ManageInfo generated by MyEclipse - Hibernate Tools
 */

public class ManageInfo  implements java.io.Serializable {


    // Fields    

     private Integer MId;
     private String MName;
     private String MPass;
     private Integer MAge;
     private Integer MSex;
     private String MTel;
     private String MAddress;
     private String MEmail;


    // Constructors

    /** default constructor */
    public ManageInfo() {
    }

	/** minimal constructor */
    public ManageInfo(Integer MId, String MName, String MPass) {
        this.MId = MId;
        this.MName = MName;
        this.MPass = MPass;
    }
    
    /** full constructor */
    public ManageInfo(Integer MId, String MName, String MPass, Integer MAge, Integer MSex, String MTel, String MAddress, String MEmail) {
        this.MId = MId;
        this.MName = MName;
        this.MPass = MPass;
        this.MAge = MAge;
        this.MSex = MSex;
        this.MTel = MTel;
        this.MAddress = MAddress;
        this.MEmail = MEmail;
    }

   
    // Property accessors

    public Integer getMId() {
        return this.MId;
    }
    
    public void setMId(Integer MId) {
        this.MId = MId;
    }

    public String getMName() {
        return this.MName;
    }
    
    public void setMName(String MName) {
        this.MName = MName;
    }

    public String getMPass() {
        return this.MPass;
    }
    
    public void setMPass(String MPass) {
        this.MPass = MPass;
    }

    public Integer getMAge() {
        return this.MAge;
    }
    
    public void setMAge(Integer MAge) {
        this.MAge = MAge;
    }

    public Integer getMSex() {
        return this.MSex;
    }
    
    public void setMSex(Integer MSex) {
        this.MSex = MSex;
    }

    public String getMTel() {
        return this.MTel;
    }
    
    public void setMTel(String MTel) {
        this.MTel = MTel;
    }

    public String getMAddress() {
        return this.MAddress;
    }
    
    public void setMAddress(String MAddress) {
        this.MAddress = MAddress;
    }

    public String getMEmail() {
        return this.MEmail;
    }
    
    public void setMEmail(String MEmail) {
        this.MEmail = MEmail;
    }
   








}