package com.xaccp.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * OrderInfo generated by MyEclipse - Hibernate Tools
 */

public class OrderInfo  implements java.io.Serializable {


    // Fields    

     private Integer OId;
     private UserInfo userInfo;
     private EnterpriseInfo enterpriseInfo;
     private FoodInfo foodInfo;
     private Integer OCount;
     private Integer OState;
     private Date OTime;
     private Set orderAccessorilies = new HashSet(0);


    // Constructors

    /** default constructor */
    public OrderInfo() {
    }

	/** minimal constructor */
    public OrderInfo(Integer OId) {
        this.OId = OId;
    }
    
    /** full constructor */
    public OrderInfo(Integer OId, UserInfo userInfo, EnterpriseInfo enterpriseInfo, FoodInfo foodInfo, Integer OCount, Integer OState, Date OTime, Set orderAccessorilies) {
        this.OId = OId;
        this.userInfo = userInfo;
        this.enterpriseInfo = enterpriseInfo;
        this.foodInfo = foodInfo;
        this.OCount = OCount;
        this.OState = OState;
        this.OTime = OTime;
        this.orderAccessorilies = orderAccessorilies;
    }

   
    // Property accessors

    public Integer getOId() {
        return this.OId;
    }
    
    public void setOId(Integer OId) {
        this.OId = OId;
    }

    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    public EnterpriseInfo getEnterpriseInfo() {
        return this.enterpriseInfo;
    }
    
    public void setEnterpriseInfo(EnterpriseInfo enterpriseInfo) {
        this.enterpriseInfo = enterpriseInfo;
    }

    public FoodInfo getFoodInfo() {
        return this.foodInfo;
    }
    
    public void setFoodInfo(FoodInfo foodInfo) {
        this.foodInfo = foodInfo;
    }

    public Integer getOCount() {
        return this.OCount;
    }
    
    public void setOCount(Integer OCount) {
        this.OCount = OCount;
    }

    public Integer getOState() {
        return this.OState;
    }
    
    public void setOState(Integer OState) {
        this.OState = OState;
    }

    public Date getOTime() {
        return this.OTime;
    }
    
    public void setOTime(Date OTime) {
        this.OTime = OTime;
    }

    public Set getOrderAccessorilies() {
        return this.orderAccessorilies;
    }
    
    public void setOrderAccessorilies(Set orderAccessorilies) {
        this.orderAccessorilies = orderAccessorilies;
    }
   








}