package com.xaccp.po;



/**
 * OrderAccessorily generated by MyEclipse - Hibernate Tools
 */

public class OrderAccessorily  implements java.io.Serializable {


    // Fields    

     private Integer oaId;
     private OrderInfo orderInfo;
     private Double oaTotalprice;


    // Constructors

    /** default constructor */
    public OrderAccessorily() {
    }

	/** minimal constructor */
    public OrderAccessorily(Integer oaId) {
        this.oaId = oaId;
    }
    
    /** full constructor */
    public OrderAccessorily(Integer oaId, OrderInfo orderInfo, Double oaTotalprice) {
        this.oaId = oaId;
        this.orderInfo = orderInfo;
        this.oaTotalprice = oaTotalprice;
    }

   
    // Property accessors

    public Integer getOaId() {
        return this.oaId;
    }
    
    public void setOaId(Integer oaId) {
        this.oaId = oaId;
    }

    public OrderInfo getOrderInfo() {
        return this.orderInfo;
    }
    
    public void setOrderInfo(OrderInfo orderInfo) {
        this.orderInfo = orderInfo;
    }

    public Double getOaTotalprice() {
        return this.oaTotalprice;
    }
    
    public void setOaTotalprice(Double oaTotalprice) {
        this.oaTotalprice = oaTotalprice;
    }
   








}