package com.xaccp.po;

import java.util.HashSet;
import java.util.Set;


/**
 * UserInfo generated by MyEclipse - Hibernate Tools
 */

public class UserInfo  implements java.io.Serializable {


    // Fields    

     private Integer UId;
     private String UName;
     private String UPass;
     private String URealName;
     private String UPaperCode;
     private Integer UAge;
     private Integer USex;
     private String UTel;
     private String UAddress;
     private String UEmail;
     private Set credits = new HashSet(0);
     private Set complainInfos =new HashSet(0);
     private Set orderInfos = new HashSet(0);


    // Constructors
	/** default constructor */
    public UserInfo() {
    }

	/** minimal constructor */
    public UserInfo(Integer UId, String UName, String UPass) {
        this.UId = UId;
        this.UName = UName;
        this.UPass = UPass;
    }
    
    /** full constructor */
    public UserInfo(Integer id, String name, String pass, String realName, String paperCode, Integer age, Integer sex, String tel, String address, String email, Set credits, Set complainInfos, Set orderInfos) {
		super();
		UId = id;
		UName = name;
		UPass = pass;
		URealName = realName;
		UPaperCode = paperCode;
		UAge = age;
		USex = sex;
		UTel = tel;
		UAddress = address;
		UEmail = email;
		this.credits = credits;
		this.complainInfos = complainInfos;
		this.orderInfos = orderInfos;
	}

   
    // Property accessors

    public Integer getUId() {
        return this.UId;
    }
    
    public void setUId(Integer UId) {
        this.UId = UId;
    }

    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }

    public String getUPass() {
        return this.UPass;
    }
    
    public void setUPass(String UPass) {
        this.UPass = UPass;
    }

    public String getURealName() {
        return this.URealName;
    }
    
    public void setURealName(String URealName) {
        this.URealName = URealName;
    }

    public String getUPaperCode() {
        return this.UPaperCode;
    }
    
    public void setUPaperCode(String UPaperCode) {
        this.UPaperCode = UPaperCode;
    }

    public Integer getUAge() {
        return this.UAge;
    }
    
    public void setUAge(Integer UAge) {
        this.UAge = UAge;
    }

    public Integer getUSex() {
        return this.USex;
    }
    
    public void setUSex(Integer USex) {
        this.USex = USex;
    }

    public String getUTel() {
        return this.UTel;
    }
    
    public void setUTel(String UTel) {
        this.UTel = UTel;
    }

    public String getUAddress() {
        return this.UAddress;
    }
    
    public void setUAddress(String UAddress) {
        this.UAddress = UAddress;
    }

    public String getUEmail() {
        return this.UEmail;
    }
    
    public void setUEmail(String UEmail) {
        this.UEmail = UEmail;
    }

    public Set getCredits() {
        return this.credits;
    }
    
    public void setCredits(Set credits) {
        this.credits = credits;
    }

    public Set getOrderInfos() {
        return this.orderInfos;
    }
    
    public void setOrderInfos(Set orderInfos) {
        this.orderInfos = orderInfos;
    }

	public Set getComplainInfos() {
		return complainInfos;
	}

	public void setComplainInfos(Set complainInfos) {
		this.complainInfos = complainInfos;
	}
}